### PR TITLE
[Timotius Jason] Add self-introduction to README

### PR DESCRIPTION
**Pull request by timotius-jason**

### CODE REVIEW

**Comment by chngchngchng** [comment]
Hello! Nice to meet you! Do I call you James or Timotius?

**Review by Justinhoejj — COMMENTED** [review]
Very cool Timotius! I too am interested in Algo trading! 📈

**Comment by timotius-jason** [comment]
> Hello! Nice to meet you! Do I call you James or Timotius?

Hey! You can call me Timo or Timotius :D

James would've been really cool though

**Comment by gnahzeus** [comment]
Hi Timo! Nice to meet you 😄

**Comment by AndreasL7** [comment]
Great to meet you Timo!

**Comment by bryanwonggy** [comment]
Hi Timo,
Nice to meet you. Hope to see you around in school!

**Comment by duofeng0110** [comment]
Hi Timotius! Very nice to meet you

**Comment by mafiom038** [comment]
Hi Timo, nice to meet you!

**Pull request closed without merging**
